Lambda( => {
try {
}
catch (Exception e) {
}
finally {
}
}
)